videobridge {
    apis {
        rest {
            enabled = true
        }
    }
    http-servers {
        public {
            port = __PORT_JVB__
        }
    }
    websockets {
        enabled = true
        domain = "__DOMAIN__:443"
        tls = true
    }
}
