#!/bin/bash

force=${2:-0}  # 0/1 --force argument
dryrun=${3:-0}  # 0/1 --dry-run argument
pending_conf=$4 # Path of the pending conf file

# Define a temporary directory
temp_dir=/tmp/jitsi.bck

# Retrieve Jitsi domain name
domain="$(yunohost app setting jitsi domain)"

do_pre_regen() {
  if [ $dryrun -eq 0 ]
  then
  # Create temporary directory
  mkdir $temp_dir

  # Backup metronome config
  cp -a "/etc/metronome/conf.d/$domain.cfg.lua" "$temp_dir/$domain.cfg.lua"
  fi
}

do_post_regen() {
  # Backup Jitsi domain files
  mv -f /etc/metronome/conf.d/$domain.cfg.lua /etc/metronome/conf.d/$domain.cfg.lua.back
  mv -f /etc/metronome/conf.d/auth.$domain.cfg.lua /etc/metronome/conf.d/auth.$domain.cfg.lua.back
  mv -f /etc/metronome/conf.d/conference.$domain.cfg.lua /etc/metronome/conf.d/conference.$domain.cfg.lua.back
  mv -f /etc/metronome/conf.d/jitsi-videobridge.$domain.cfg.lua /etc/metronome/conf.d/jitsi-videobridge.$domain.cfg.lua.back
  mv -f /etc/metronome/conf.d/focus.$domain.cfg.lua /etc/metronome/conf.d/focus.$domain.cfg.lua.back
  
  # Restore metronome config
  cp -f "$temp_dir/$domain.cfg.lua"  "/etc/metronome/conf.d/$domain.cfg.lua"

  # Delete temporary directory
  test -n $temp_dir && rm -r $temp_dir

  # Reload metronome
  systemctl reload metronome
}

case "$1" in
  pre)
    do_pre_regen
    ;;
  post)
    do_post_regen
    ;;
  *)
    echo "Hook called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac
