#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INSTALL JITSI
#=================================================

echo jitsi-videobridge2 jitsi-videobridge/jvb-hostname string "$domain"   | debconf-set-selections
echo jitsi-meet-web-config jitsi-meet/cert-choice string "I want to use my own certificate"  | debconf-set-selections
echo jitsi-meet-web-config jitsi-meet/cert-path-key string "/etc/yunohost/certs/$domain/key.pem" | debconf-set-selections
echo jitsi-meet-web-config jitsi-meet/cert-path-crt string "/etc/yunohost/certs/$domain/crt.pem" | debconf-set-selections
echo jitsi-meet-web-config jitsi-meet/jaas-choice select false | debconf-set-selections

ynh_apt_install_dependencies_from_extra_repository --repo="deb https://download.jitsi.org stable/" --package="jitsi-meet prosody-modules" --key="https://download.jitsi.org/jitsi-key.gpg.key"

#=================================================
# LDAP CONFIGURATION
#=================================================

if [ $enable_ldap -eq 1 ]
then
    ynh_script_progression "Configuring LDAP..."
    _enable_ldap
fi

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_safe_rm "/etc/nginx/sites-enabled/$domain.conf"

ynh_config_add_nginx

yunohost service add "jitsi-videobridge2" --log="/var/log/jitsi/jvb.log" --needs_exposed_ports "$port" "$port_videobridge"

yunohost service add "jicofo" --log="/var/log/jitsi/jicofo.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="prosody" --action="restart" --log_path="/var/log/prosody/prosody.log"
ynh_systemctl --service="jicofo" --action="restart" --log_path="/var/log/jitsi/jicofo.log"
ynh_systemctl --service="jitsi-videobridge2" --action="restart" --log_path="/var/log/jitsi/jvb.log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
