#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================
ynh_print_info --message="Loading installation settings..."

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get --app=$app --key=domain)
port=$(ynh_app_setting_get --app=$app --key=port)
port_videobridge=$(ynh_app_setting_get --app=$app --key=port_videobridge)
port_component=$(ynh_app_setting_get --app=$app --key=port_component)
final_path=$(ynh_app_setting_get --app=$app --key=final_path)
focus_user=$(ynh_app_setting_get --app=$app --key=focus_user)

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE SERVICE INTEGRATION IN YUNOHOST
#=================================================
ynh_print_info --message="Removing service integration in YunoHost..."

# Remove the service from the list of services known by Yunohost (added from `yunohost service add`)
if ynh_exec_warn_less yunohost service status $app-videobridge >/dev/null
then
	ynh_print_info --message="Removing $app-videobridge service..."
	yunohost service remove $app-videobridge
fi

if ynh_exec_warn_less yunohost service status $app-jicofo >/dev/null
then
	ynh_print_info --message="Removing $app-jicofo service..."
	yunohost service remove $app-jicofo
fi

#=================================================
# STOP AND REMOVE SERVICE
#=================================================
ynh_print_info --message="Stopping and removing the systemd service..."

# Remove the dedicated systemd config
ynh_remove_systemd_config --service=$app-videobridge
ynh_remove_systemd_config --service=$app-jicofo

#=================================================
# REMOVE DEPENDENCIES
#=================================================
ynh_print_info --message="Removing dependencies..."

# Remove metapackage and its dependencies
ynh_remove_app_dependencies

ynh_remove_nodejs

#=================================================
# REMOVE APP MAIN DIR
#=================================================
ynh_print_info --message="Removing app main directory..."

# Remove the app directory securely
ynh_secure_remove --file="$final_path"

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================
ynh_print_info --message="Removing nginx web server configuration..."

# Remove the dedicated nginx config
ynh_remove_nginx_config

#=================================================
# REMOVE LOGROTATE CONFIGURATION
#=================================================
ynh_print_info --message="Removing logrotate configuration..."

# Remove the app-specific logrotate config
ynh_remove_logrotate

#=================================================
# CLOSE A PORT
#=================================================
ynh_print_info --message="Closing a port..."

if yunohost firewall list | grep -q "\- $port$"
then
	ynh_print_info --message="Closing port $port..."
	ynh_exec_warn_less yunohost firewall disallow TCP $port
fi

if yunohost firewall list | grep -q "\- $port_videobridge$"
then
	ynh_print_info --message="Closing port $port_videobridge..."
	ynh_exec_warn_less yunohost firewall disallow UDP $port_videobridge
fi

if yunohost firewall list | grep -q "\- $port_component$"
then
	ynh_print_info --message="Closing port $port_component..."
	ynh_exec_warn_less yunohost firewall disallow TCP $port_component
fi

#=================================================
# SPECIFIC REMOVE
#=================================================
# RECONFIGURE METRONOME
#=================================================
ynh_print_info --message="Reconfiguring Metronome..."

# Remove Metronome modules
ynh_secure_remove --file="/usr/lib/metronome/modules/mod_http_altconnect.lua"

ynh_systemd_action --service_name=metronome --action=restart

# Remove domain conf template
ynh_secure_remove --file="/usr/share/yunohost/templates/jitsi/$domain.cfg.lua"
ynh_secure_remove --file="/usr/share/yunohost/templates/jitsi/auth.$domain.cfg.lua"
ynh_secure_remove --file="/usr/share/yunohost/templates/jitsi/conference.$domain.cfg.lua"
ynh_secure_remove --file="/usr/share/yunohost/templates/jitsi/jitsi-videobridge.$domain.cfg.lua"
ynh_secure_remove --file="/usr/share/yunohost/templates/jitsi/focus.$domain.cfg.lua"

# Remove Jitsi template directory
if [ -z "$(ls -A /usr/share/yunohost/templates/jitsi)" ]; then
   ynh_secure_remove --file="/usr/share/yunohost/templates/jitsi"
fi

# Remove Metronome Hook
ynh_secure_remove --file="/usr/share/yunohost/hooks/conf_regen/50-metronome_$app"
yunohost tools regen-conf metronome

# Delete focus user
yunohost user delete $focus_user --purge

# Removing additional domains
if [ ${PACKAGE_CHECK_EXEC:-0} -eq 1 ]; then
	yunohost domain remove auth.$domain
	yunohost domain remove conference.$domain
	yunohost domain remove jitsi-videobridge.$domain
	yunohost domain remove focus.$domain
fi

#=================================================
# REMOVE THE LOG FILES
#=================================================

# Remove the log files
ynh_secure_remove --file="/var/log/$app"

#=================================================
# GENERIC FINALIZATION
#=================================================
# REMOVE DEDICATED USER
#=================================================
ynh_print_info --message="Removing the dedicated system user..."

# Delete a system user
ynh_system_user_delete --username=$app

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info --message="Removal of $app completed"
